"""First migration, adding four main tables

Revision ID: 2ee4066a689b
Revises: 
Create Date: 2024-11-04 05:18:39.300138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2ee4066a689b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('anthropometricmeasurments',
    sa.Column('anthropometric_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('height', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('anthropometric_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('metricbatch',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('healthmetrics',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['metricbatch.batch_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthmetrics')
    op.drop_table('metricbatch')
    op.drop_table('anthropometricmeasurments')
    op.drop_table('user')
    # ### end Alembic commands ###
