"""added new column avg_inter_beat_interval

Revision ID: 4d8d2b3eff71
Revises: c22111eb99f8
Create Date: 2025-04-01 04:23:53.654097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4d8d2b3eff71'
down_revision: Union[str, None] = 'c22111eb99f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregatedhealthmetrics', sa.Column('avg_inter_beat_interval', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregatedhealthmetrics', 'avg_inter_beat_interval')
    # ### end Alembic commands ###
