"""added new column avg_heart_rate_variability

Revision ID: 4ecc0f08271d
Revises: 4d8d2b3eff71
Create Date: 2025-04-01 05:02:16.927585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4ecc0f08271d'
down_revision: Union[str, None] = '4d8d2b3eff71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregatedhealthmetrics', sa.Column('avg_heart_rate_variability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregatedhealthmetrics', 'avg_heart_rate_variability')
    # ### end Alembic commands ###
