"""Fixed table name

Revision ID: 781077a91823
Revises: 2ee4066a689b
Create Date: 2024-11-04 18:46:59.364710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '781077a91823'
down_revision: Union[str, None] = '2ee4066a689b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthropometricmeasurements',
    sa.Column('anthropometric_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('height', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('anthropometric_id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('anthropometricmeasurments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthropometricmeasurments',
    sa.Column('anthropometric_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('weight', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='anthropometricmeasurments_user_id_fkey'),
    sa.PrimaryKeyConstraint('anthropometric_id', name='anthropometricmeasurments_pkey'),
    sa.UniqueConstraint('user_id', name='anthropometricmeasurments_user_id_key')
    )
    op.drop_table('anthropometricmeasurements')
    # ### end Alembic commands ###
