"""added aggregate table

Revision ID: a3dda622c686
Revises: bc64b61b0232
Create Date: 2025-03-17 23:09:43.086395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a3dda622c686'
down_revision: Union[str, None] = 'bc64b61b0232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregatedhealthmetrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('current_heart_rate', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Float(), nullable=True),
    sa.Column('min_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('heart_rate_variability', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregatedhealthmetrics_id'), 'aggregatedhealthmetrics', ['id'], unique=False)
    op.create_index(op.f('ix_aggregatedhealthmetrics_user_id'), 'aggregatedhealthmetrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aggregatedhealthmetrics_user_id'), table_name='aggregatedhealthmetrics')
    op.drop_index(op.f('ix_aggregatedhealthmetrics_id'), table_name='aggregatedhealthmetrics')
    op.drop_table('aggregatedhealthmetrics')
    # ### end Alembic commands ###
