"""Added IBI and Respiratory Rate

Revision ID: c22111eb99f8
Revises: a3dda622c686
Create Date: 2025-03-22 22:40:54.384209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c22111eb99f8'
down_revision: Union[str, None] = 'a3dda622c686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregatedhealthmetrics', sa.Column('inter_beat_interval', sa.Float(), nullable=True))
    op.add_column('aggregatedhealthmetrics', sa.Column('respiratory_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregatedhealthmetrics', 'respiratory_rate')
    op.drop_column('aggregatedhealthmetrics', 'inter_beat_interval')
    # ### end Alembic commands ###
