services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: aaa_health_fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    volumes:
      - ./app:/app  # Sync the app directory for live code changes
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Enables auto-reload for FastAPI